import React, { useState, useEffect } from 'react';
import { useFormContext } from 'react-hook-form';
import { categoryApi } from '../../../api';
import { Loader2 } from 'lucide-react';

const Step1Basic = () => {
  const { register, formState: { errors } } = useFormContext();
  const [categories, setCategories] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    categoryApi.getAll()
      .then(data => setCategories(data))
      .catch(err => console.error(err))
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="space-y-6">
      <h2 className="text-xl font-bold text-gray-900 border-b border-gray-100 pb-3">Basic Information</h2>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Product Name <span className="text-red-500">*</span></label>
          <input 
            type="text" 
            {...register('name', { required: 'Name is required' })}
            className={`w-full px-4 py-2.5 border rounded-lg outline-none focus:ring-2 focus:ring-purple-200 transition-colors ${errors.name ? 'border-red-500 bg-red-50' : 'border-gray-300 focus:border-purple-500 bg-gray-50'}`}
            placeholder="E.g., Bronze Ganesh Statue"
          />
          {errors.name && <p className="text-red-500 text-xs mt-1 font-medium">{errors.name.message}</p>}
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Slug</label>
          <input 
            type="text" 
            {...register('slug')}
            className="w-full px-4 py-2.5 border border-gray-300 rounded-lg outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-200 bg-gray-50 transition-colors"
            placeholder="Auto-generated if empty"
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">SKU</label>
          <input 
            type="text" 
            {...register('sku')}
            className="w-full px-4 py-2.5 border border-gray-300 rounded-lg outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-200 bg-gray-50 transition-colors opacity-70 cursor-not-allowed"
            placeholder="Auto-generated by system"
            readOnly
          />
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Category <span className="text-red-500">*</span></label>
          <div className="relative">
            <select 
              {...register('category', { required: 'Category is required' })}
              className={`w-full px-4 py-2.5 appearance-none border rounded-lg outline-none focus:ring-2 focus:ring-purple-200 transition-colors ${errors.category ? 'border-red-500 bg-red-50' : 'border-gray-300 focus:border-purple-500 bg-gray-50'}`}
            >
              <option value="">Select Category</option>
              {categories.map(cat => (
                <option key={cat._id} value={cat._id}>{cat.name}</option>
              ))}
            </select>
            {loading && <Loader2 size={16} className="absolute right-3 top-3 animate-spin text-gray-400" />}
          </div>
          {errors.category && <p className="text-red-500 text-xs mt-1 font-medium">{errors.category.message}</p>}
        </div>

        <div>
          <label className="block text-sm font-medium text-gray-700 mb-1">Product Type <span className="text-red-500">*</span></label>
          <select 
            {...register('productType')}
            className="w-full px-4 py-2.5 border border-gray-300 rounded-lg outline-none focus:border-purple-500 focus:ring-2 focus:ring-purple-200 bg-gray-50 transition-colors"
          >
            <option value="Fixed Price">Fixed Price / Standard Asset</option>
            <option value="Custom">Custom Order / Estimate Required</option>
          </select>
        </div>
      </div>
    </div>
  );
};

export default Step1Basic;
